server:
  port: 8080

spring:
  profiles:
    active: qa
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
          microsoft:
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Microsoft
        provider:
          microsoft:
            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            user-name-attribute: name

logging:
  file:
    output-dir: src/main/java/org.example/logs/ai-responses

llm:
  active-provider: groq

  groq:
    api-key: ${API_KEY}
    base-url: https://api.groq.com/openai/v1
    model: llama-3.1-8b-instant

  openai:
    api-key: ${OPENAI_API_KEY}
    base-url: https://openai/v1
    model: gpt-4o-mini
